os: osx
# to run this on Mac OS
language: objective-c
cache: bundler
rvm:
  - system
  - 2.2.1
  - 2.2.2
  - 2.1.5
  - 2.0.0
  - 1.9.3


before_install:
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - sudo gem install bundler

script: bundler exec rspec --pattern **/*_spec.rb
